<a href="https://colab.research.google.com/github/audalsgh/20250702/blob/main/0702_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy 패키지는 import numpy as np 로 임포팅한다

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


.__version__ 입력시 numpy 버전을 체크가능

In [ ]:
import numpy as np

print(np.__version__)

2.0.2


numpy로 0차원, 1차원, 2차원, 3차원 배열을 만들었다.

In [ ]:
import numpy as np

arr0 = np.array(42)
print(arr0,'\n')

arr1 = np.array([1,2,3,4,5])
print(arr1,"\n")

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2,"\n")

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

42 

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


numpy의 차원을 알아보는 .ndim 문법

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


한번에 고차원의 numpy 배열을 만드는 법은 ndim = 5 로 줘버리는 것.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


numpy배열에 접근하는 법은 인덱스 접근과 동일하게 []이다.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])

print(arr[2] + arr[3])

1
7


2차원 배열에 접근하려면 [행, 열]

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr[0, 1],'\n')

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


3차원 배열에 접근하려면 [윗차원, 행, 열]

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


음수 인덱스로 접근하면, 가장 마지막 인덱스를 의미한다.

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


배열 슬라이싱 문법은 arr[1:5] 이다. arr[4:] 이렇게 끝을 지정하지 않으면 끝까지 슬라이싱한다.
- arr[-3:-1] 이면 끝에서 1칸 떨어진 부분~ 끝에서 3칸떨어진 부분 = 4번,5번 인덱스
- arr[1:5:2] 이면 2칸 간격으로 1~5번 인덱스를 슬라이싱 (*마지막은 미포함!)
- arr[::2] 이면 2칸 간격으로 모든 인덱스를 슬라이싱 (*마지막도 포함!)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr,'\n')
print(arr[1:5])
print(arr[4:])
print(arr[:4])

print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[1 2 3 4 5 6 7] 

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


2차원 배열 슬라이싱
- arr[행, 인덱스:범위]
- arr[인덱스:범위, 열]
- arr[인덱스:범위, 인덱스:범위] (*마지막인덱스 미포함!)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr,'\n')
print(arr[1, 1:4],'\n')
print(arr[0:2, 2],'\n')
print(arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[7 8 9] 

[3 8] 

[[2 3 4]
 [7 8 9]]


np 배열에 저장된 데이터가 무슨 종류인지 알아보는 .dtype 문법

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


저장된 데이터의 종류를 바꿔주는 'S', 'i', 'b' 등등의 문법이 있다. (순서대로 string, int, bool)
단, 섞여선 안된다.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype,'\n')

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1 

[1 2 3 4]
int32


arr.as type('i') 를 써서 실수가 담긴 배열을 정수로 바꿨다. arr.astype(int)도 가능!

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype,'\n')

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32 

[1 2 3]
int64


파이썬은 0만 false고, 나머지값은 모두 true로 본다.

In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


np배열의 복사본을 만드는 arr.copy() 문법. 원본영향x

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


np배열 원본을 복제하는 arr.view() 문법. 원본이 변할시 변한 모습 그대로 전달받음

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


np배열 원본을 복제하는 arr.view() 문법. 사본이 변하면 원본도 변함

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


arr.base는 원본을 의미한다. arr.copy()는 원본을 건드리지 못하니 none이라고 뜨는것!

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


arr.shape 로 차원과 원소가 몇개인지 출력해볼수있다.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


5차원에만 값이 4개있는 배열의 경우, 나머지 차원은 크기가 1이고 마지막 차원은 4개의 인덱스라고 출력된다

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


arr.reshape(행,열) 로 차원을 늘릴수있다. arr.reshape(차원, 행, 열) 도 가능.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr,'\n')

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


arr.reshape(행,열) 을 사용해도, 원본을 건드리지 않았기 때문에 .base로 확인해보면 view와 마찬가지로 원본이 나온다

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


arr.reshape(행,열, -1) 이면 자동으로 나머지 차원이 계산되어 (2x2)행렬이 두개 놓인 3차원이 된다.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


arr.reshape(-1) 을 주면, 1차원 배열로 내려온다.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
newarr = arr.reshape(-1)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


for문으로 np배열을 순회할수 있고, 2차원이면 이중for문, 3차원이면 삼중for문을 쓰면됨.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
for x in arr:
  print(x)
print('\n')

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
print('\n')

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)
print('\n')

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
print('\n')

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3


[1 2 3]
[4 5 6]


1
2
3
4
5
6


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


1
2
3
4
5
6
7
8
9
10
11
12


몇중for문일지 귀찮다면, np.nditer(arr)로 for문을 돌리면 자동으로 계산된다

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


기본 이터레이터는 배열을 한 번에 메모리 뷰(view)로 순회하는데,
buffered 플래그를 주면 내부적으로 버퍼를 사용해
dtype 변환이 필요한 경우에도 안전하게 순회할 수 있게 함.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


arr[:, ::2] 모든차원에 대해, 2칸간격으로 마지막도 포함하여 슬라이싱!

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


np.ndenumerate는 배열의 각 요소를 순회하면서 인덱스(좌표)와 값을 동시에 반환해 주는 이터레이터.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)
print('\n')

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8




---



np.concatenate((arr1,arr2)) 문법으로 두 배열을 합칠수 있다.
- axis = 0 인자를 주면 행 진행방향 = 아래로 붙힌 (4x2) 배열이 됨
- axis = 1 인자를 주면 열 진행방향 = 우측옆으로 붙힌 (2x4) 배열이 됨

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
print('-'*30)

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------------------
[[1 2 5 6]
 [3 4 7 8]]


np.stack((arr1,arr2)) 문법으로도 두 배열을 합칠수 있고, 결정적으로 차원이 늘어난다.
- axis = 0 인자로 주면 (2x2)배열 두개가 단순 겹쳐진 3차원의 결과
- axis = 1 인자로 주면 (2x2)배열 두개가 새로생긴 3차원에 걸쳐서 겹친 3차원의 결과

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2), axis=0)
print(arr)
print('-'*30)

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


np.hstack()과 np.vstack()은 각각 행에 붙히기, 열에 붙히기.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print('-'*30)

arr = np.vstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
------------------------------
[[1 2 3]
 [4 5 6]]


np.dstack((arr1,arr2))은 내부적으로 각각을 (1x3)열 벡터로 바라보고, 입력배열 갯수인 2만큼 차원을 갖는다.
- (3x2)배열처럼 보이지만, 대괄호가 3개이므로 3차원!

In [155]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


np.array_split(arr,3) 메소드로 두번째 인자로 준 갯수만큼 배열을 얻을수있다.<br>
짝수가 맞지않아도 마지막 부분에서 자동으로 쪼개진다.<br>
-> 쪼개진 배열도 당연히 []인덱스로 접근 가능

In [161]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 4)
print(newarr)

print()
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]

[1 2]
[3 4]
[5]


출력 개행이 이상할 뿐이지, _split() 메소드는 배열을 두번째 인자만큼 쪼개는 것이다

In [163]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


(1x3)배열들을 원소로하는 arr를, 똑같이 3묶음 = (2x3)배열이 3개가 되도록 만든다.<br>주어진 배열이 (6x3)일때, axis = 1을 주면 (nx1)열 벡터 3개로 나뉜다.

In [167]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


np.hsplit() 메소드 역시 큰 배열을 두번째 인자 갯수만큼의 작은 배열로 나눠주지만, 차이점은 균등 분할이 가능한 사이즈끼리여야 한다는 것.

In [169]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


np.where(arr == 4 등의 조건들)을 만족하는 지점의 인덱스를 찾아냄.

In [174]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

x = np.where(arr%2 == 1)
print(x)

(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


np.searchsorted(arr, 7, side = 'right') 메소드는 7이 등장하는 첫 인덱스를 반환하는데, 'right'를 인자로 주면 오른쪽부터 탐색을 시작한다

In [181]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

x = np.searchsorted(arr, 7, side='right')
print(x)

1
2


np.searchsorted()에 배열을 인자로 넣으면, "크기순으로 정렬되있는 원래 배열"을 왼쪽부터 탐색해가며 2,4,6이 들어갈 위치의 인덱스를 배열로 반환한다

In [183]:
import numpy as np

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


np.sort() 메소드는 숫자는 크기 작은순, 문자는 알파벳순, 부울은 false부터 오름차순으로 정리한다

In [187]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

arr = np.array([True, False, True])
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


np.sort() 메소드에 2차원 배열을 넣으면, 배열 형태는 건들지않고 내부만 크기순으로 정렬한다

In [189]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


numpy의 필터 개념 : np.array 배열과 같은 길이의 부울 배열 x를 새로 만들고, True를 갖는 인덱스만 남기도록 newarr = arr[x]라 적는다.

In [191]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


필터 조건도 직접 for문을 돌려서 리스트에 만들수있다.<br>
리스트 메소드의 .append(True)를 이용해 필터 리스트를 채워나간다.

In [195]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


이번엔 필터 조건이 짝수일뿐, 위 문제와 동일하다

In [197]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


필터 조건을 복잡한 for문을 쓰지않고, arr > 42 라는 한 문장으로 적어줬다.<br>
기존 arr 배열을 순회하며 42보다 작은 경우 자동으로 False가 채워지고, 42보다 큰 경우 자동으로 True가 채워진다.

In [199]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


역시 위와 똑같은 문제에서 조건만 짝수로 변한것. 한 문장에 필터 조건을 적은 것은 동일하다.

In [200]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
